# LeNet
MNIST_DIMENSIONS = 784
MNIST_WIDTH = 28
MNIST_HEIGHT = 28
HIDDEN_LAYER_ONE_CHANNELS = 128
HIDDEN_LAYER_TWO_CHANNELS = 128

# Conv Net
CONV_ONE_FILTERS = 5
KERNEL_SIZE = 5
STRIDE = 2

FC_LAYER_ONE_UNITS = 100

NUM_CLASSES = 10
NUM_SAMPLES = 100
NUM_EPOCHS = 10
LEARNING_RATE = 0.001
MOMENTUM = 0.9
BATCH_SIZE = 8
TEST_BATCH_SIZE = 200

TRAINING_PARAMS = {
        'learning_rate': LEARNING_RATE,
        'momentum': MOMENTUM,
        'num_epochs': NUM_EPOCHS
}

ALICE = 0
BOB = 1

LENET_MODEL_PATH = '../models/alice_model.pth'
CONVNET_MODEL_PATH = '../models/alice_conv_model.pth'

